[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["python -m pip install -r requirements.txt"]

[phases.build]
cmds = [
    "python manage.py collectstatic --no-input",
    "python manage.py migrate --no-input"
]

[start]
cmd = "gunicorn warranty_vault.wsgi:application --bind 0.0.0.0:$PORT"
